### ISSUE TITLE
Refomating "Kolla din e-mail"

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#112]
The star in "Kod*" should be removed
![image](https://user-images.githubusercontent.com/41542666/103212131-546f1a00-490a-11eb-9897-30eb7bad7ed2.png)
This is how notion does it:
![image](https://user-images.githubusercontent.com/41542666/103212193-7ec0d780-490a-11eb-94a2-1d1b8a29353b.png)

**Comment by Nautman** [comment]
The star is there since it is a required field. Do you think we should [bypass the specification](https://github.com/mui-org/material-ui/issues/10274)?

**Comment by Zigolox** [comment]
I think it is very obvious and the star doesn't make it more obvious

**Comment by Zigolox** [comment]
@charlesmaddock or @sakerhetspolisen might have a better solution.
