### ISSUE TITLE
Fields that should be requered doesn't have a star in settings

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#121]
![image](https://user-images.githubusercontent.com/41542666/103223989-67dcae00-4927-11eb-9ae9-254df614fe7f.png)

![image](https://user-images.githubusercontent.com/41542666/103224011-6e6b2580-4927-11eb-9f1e-13ec2ca1071f.png)

**Comment by simonthor** [comment]
The field "Könsidentitet" in the "create account" page is also missing a *, as seen in this image: ![](https://user-images.githubusercontent.com/45770021/103423619-e5aeec80-4ba7-11eb-8c08-c6fe62120898.png)
