### ISSUE TITLE
Validation of username/email does not work

### ISSUE THREAD

**Issue by kelszo** [digitalungdom-se/digitalungdom.se#14]
The front-end validation of username/email does not work on signing up

Screenshot:
![image](https://user-images.githubusercontent.com/41587072/69356207-5be1df80-0c83-11ea-95da-5fcdd353ae60.png)

Confirmed on both firefox and chromium

**Comment by charlesmaddock** [comment]
Sorry, I am having a hard time seeing what the problem is here. Is it that two error messages show up whilst trying to create a password?

**Comment by kelszo** [comment]
> Sorry, I am having a hard time seeing what the problem is here. Is it that two error messages show up whilst trying to create a password?

The username and email is taken so an error should be displayed to warn the user.

**Comment by charlesmaddock** [comment]
> > Sorry, I am having a hard time seeing what the problem is here. Is it that two error messages show up whilst trying to create a password?
> 
> The username and email is taken so an error should be displayed to warn the user.

I understand, might be able to fix this in the coming days!

**Comment by Nautman** [comment]
This works in the rewrite.
