### ISSUE TITLE
The comment should be placed first in list

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#21]
The comment should be placed first and get a colored tint to show that the user commented

**Comment by Zigolox** [comment]
I think it will make it easier to know that you have posted something. Now you have to scroll the way down to see your comment

**Comment by Nautman** [comment]
The comment is now placed at the top. Is it still necessary to have a tint?

**Comment by Nautman** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/28629647/99546651-8ce81380-29ae-11eb-974d-f217f26e057c.png">

**Comment by Nautman** [comment]
Actually, I have a problem with dark mode so this isn't fixed yet.
