### ISSUE TITLE
Missing logo routes

### ISSUE THREAD

**Issue by kelszo** [digitalungdom-se/digitalungdom.se#33]
The following routes are missing
https://digitalungdom.se/static/logo.svg
https://digitalungdom.se/static/logo.png

Solution: CDN?

**Comment by Zigolox** [comment]
Is this the case @Nautman now when we are using netlify?

**Comment by Nautman** [comment]
No, it isn't. However, Netlify is missing an update that makes it possible to see this. But it will be resolved any time. I'm closing this.
