### ISSUE TITLE
You have to crop profile image

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#34]
Why selecting the profile image it shouldn't be necessary to crop the iimage. It should instead default to using the full image size.

**Comment by Nautman** [comment]
Wouldn't this be problematic with the dimensions? Which part of the profile picture would you show? Would you squeeze it? @Zigolox

**Comment by Zigolox** [comment]
I think it would be problematic so feel free to close this issue

**Comment by Nautman** [comment]
OK. Thanks for your feedback and attention! We'd rather have issues such as this one where we have a discussion and close early than no issues at all.
