### ISSUE TITLE
Improve design of Verify Email Page

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom.se#39]
The current page to verify email in the rewrite doesn't look very developed right now.

It would be nice to have a sort of Anna-inbox emote / picture, instead of the boring icon. Inspiration can be taken from Bender (in S04E08 Crimes of the Hot).
<img src="https://user-images.githubusercontent.com/28629647/83967484-6c6d4680-a8b1-11ea-9109-f72e316eebb2.png" width="50%" alt="bender got mail">
Perhaps @charlesmaddock could look into creating such a picture / emote? :)

I have created an initial storybook for the component. It is found at `features/auth/VerifyEmailPage.stories.tsx`.

**Comment by Nautman** [comment]
Please create a branch and a pull request to fix this issue.

**Comment by Nautman** [comment]
I forgot to mention that this page will be seen in 

1. a Dialog (such as the Login or Register ones)
2. a paper page, such as the Register page.

If need arises, I can clarify this by adding these examples to the Storybook.

**Comment by Nautman** [comment]
Perhaps this component can follow the style or be turned into the `VerifyEmailLink` component, see pull request #41 .

**Comment by Zigolox** [comment]
@Nautman Is this still relevant?

**Comment by Nautman** [comment]
Yes. The current design looks like this.
<img width="479" alt="image" src="https://user-images.githubusercontent.com/28629647/99582578-385a8d80-29da-11eb-901d-5e86cfb4dbad.png">

**Comment by Zigolox** [comment]
I think you could replace the mail icon with Anna [verify](https://github.com/digitalungdom-se/assets/tree/master/png/other). It could also be a continuation of the login popup instead of being its own card similar to how notion does it.

**Comment by Nautman** [comment]
I think the reason why I chose to have make it an independent card is that it uses the same logic as once you have registered. It feels weird to have a continuation on the Register page.

**Comment by Zigolox** [comment]
Okey, what does @charlesmaddock think?

**Comment by Nautman** [comment]
It's worth mentioning that it would be neat to have an automatic link to their inbox.

For example, 

1. @gmail.com: `mail.google.com`
2. @protonmail.com:`mail.protonmail.com`
3. yahoo
4. etc.

However, I'm not sure if there is a curated list already made or if we have to make one.

**Comment by Nautman** [comment]
Perhaps like this one, except this one is outdated: https://github.com/bkonetzny/link-to-inbox

**Comment by Nautman** [comment]
This is the MVP.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/28629647/101258139-61885700-3718-11eb-9c20-a715b82c1798.png">
