### ISSUE TITLE
Add information on data storage

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom.se#44]
Several members of Digital Ungdom have inquired as to how we store passwords, and if they can trust us. Since our organization strives to be transparent, it would be nice to have a page / explanation on how we store passwords. @Zigolox has previously commented on this issue.

I would like these questions to be answered:
1. Where should the information be placed? At the login or register page in a question mark icon?
2. How should the information be displayed? In a popup or on a specific page / GitHub link?
3. What should the information say?

If someone helps clarify point 1 & 2, I can take the lead on developing the necessary front-end. I would be very grateful if someone could give input on point 3.

I'm assigning Simon (@Zigolox) to take care of this issue. Of course, this doesn't mean that he necessarily has to write code. Simply manage the issue 😄

**Comment by Nautman** [comment]
An idea is to link to GitHub source code (for curious users!).

**Comment by Zigolox** [comment]
1.  The information should be placed on the side the login box as a hover hoverable questionmark.
2. As a small popup 
3. where we say it will be hashed as (@kelszo knows what) and a link to the github source page.

**Comment by Nautman** [comment]
Great! I'll look into this. I'm labeling this is a low priority for now.

I should probably have phrased my question better regarding if it should be either a [dialog](https://material-ui.com/components/dialogs/) or a [tooltip](https://material-ui.com/components/tooltips/).

I think I will create a tooltip with HTML that is interactive (meaning it doesn't fade away if you hover over the actual tooltip text).

**Comment by Nautman** [comment]
Or maybe the component could be a [popover](https://material-ui.com/components/popover/#popover)!

**Comment by Nautman** [comment]
I'd like a decision on whether this is still necessary, given that we no longer use passwords. @Zigolox

**Comment by Nautman** [comment]
We don't have passwords anymore.
