### ISSUE TITLE
Password strength

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom.se#46]
@Zigolox has mentioned that he would like to see an entropy measuring bar.

He mentions that it should go from red, to yellow, to green. It should also say how we calculate the entropy.

**Comment by Nautman** [comment]
Should it look like this?

![gif](https://raw.githubusercontent.com/angular-material-extensions/password-strength/HEAD/assets/v3.2.0/demo.gif)

Or should it not display tips?

**Comment by Zigolox** [comment]
Entropy is enough but i like more bars that goes from red to yellow to green based on the number if entropy. We could perhaps display some tips but it then seems like it is a must.

**Comment by Nautman** [comment]
I agree that it seems like a "must" if you include tips / advice.

I think perhaps some information regarding the entropy meter could be displayed in the same dialog / tooltip that displays information on how we store passwords (see #44 ). Perhaps that will be confusing though?

I'm labeling this as low priority for now.

**Comment by Nautman** [comment]
Passwords are removed. Perhaps a new issue can be created stating how we handle security with emails and why we don't want to use passwords anymore.
