### ISSUE TITLE
When pressing the downwards arrow in the radiobuttons list it should move to the next row instead of next column

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#49]
When pressing the downwards arrow i should move to the next row and not the next column:
![image](https://user-images.githubusercontent.com/41542666/85921806-2fc4b780-b87f-11ea-90a1-3ada4d27b366.png)
Should not move here:
![image](https://user-images.githubusercontent.com/41542666/85921899-ddd06180-b87f-11ea-8374-c422161d63fd.png)
It should move here
![image](https://user-images.githubusercontent.com/41542666/85921902-e3c64280-b87f-11ea-9653-3b441016974c.png)

**Comment by Nautman** [comment]
Thanks for the issue! The code for this component is found in #48!

**Comment by Nautman** [comment]
I've added the ability to programmatically set focus to a radio. This allows us to set focus to whichever radio we want.

All that is needed now is a function to correctly calculate new indexes for the focused radio. For example, a naive function would use `index + gridWidth` (gridWidth = 4 in your picture). However, this doesn't take into account the list of the grid. Therefore a better function could use `(index + gridWidth) % gridLength`. However, this function causes problems when gridLength isn't evenly divisible by gridWidth.

I challenge you @Zigolox , or anyone else for that matter, to make a new function. If you would like test data or some clarifications I can provide some. This is the outline for the current function:

```ts
const calcModuloGrid = (
index: number, direction: 'up' | 'down', gridLength: number, gridWidth: number): number => {
  switch (direction) {
    case 'up':
      return (index - gridWidth) % gridLength;
    case 'down':
      return (index + gridWidth) % gridLength;
  }
};
```

**Comment by Nautman** [comment]
Tip: Make sure you don't get negative indexes when using JavaScript modulus operator. See this [thread for explanation and how to correctly calculate modulus](https://stackoverflow.com/questions/4467539/javascript-modulo-gives-a-negative-result-for-negative-numbers).

Good luck!

**Comment by Nautman** [comment]
I made a small playground that you can test with on codepen. It handles the case where there are 17 elements and a gridLength of 4.

The `calc` function is the one that you're supposed to edit. Green indexes are correct and red are wrong.

https://codepen.io/tab/pen/pogdvQj

**Comment by Zigolox** [comment]
Hi, I created this typescript code...
```ts
function calcModuloGrid(index: number, direction: 'up' | 'down', gridLength: number, gridWidth: number): number {
  switch (direction) {
    case 'up':
      if (index - gridWidth + 1 <= 0) {
        if (index <= (gridLength - 1) % gridWidth) return gridLength - 1 - ((gridLength - 1) % gridWidth) + index;
        else return gridLength - 1 - ((gridLength - 1) % gridWidth) - gridWidth + index;
      } else return index - gridWidth;
    case 'down':
      if (index + gridWidth >= gridLength) return index % gridWidth;
      else return index + gridWidth;
    default:
      return index;
  }
}
```

**Comment by Nautman** [comment]
Great, thanks a lot Simon! I'll incorporate it immediately and close the issue.

I had an idea to also implement motion in east and west direction, but I don't think it's necessary to do this right now. Maybe you think it is?

**Comment by Zigolox** [comment]
What do you mean with east and west? Left and right?

**Comment by Nautman** [comment]
Yes, I mean left and right @Zigolox. I've implemented a fix. Thank you for your help!

Since this issue relates to a branch that hasn't yet been merged and that the branch has implemented this fix, I'm closing this issue.
