### ISSUE TITLE
Add check for age under 13 under sign-up

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#58]
Add check for age under 13
If the age is under 13:
   Send mail to parent specified in a new mail field.
Parent must send email with consent to one of our emails.

**Comment by Zigolox** [comment]
Could we at least add a check for this front-end so it sends an error to the user telling them to send an email to styrelse@digitalungdom.se @Nautman?

**Comment by Nautman** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/28629647/99585064-bbc9ae00-29dd-11eb-9885-b77e5be3d791.png">
