### ISSUE TITLE
Translations for entire website

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom.se#65]

**Comment by Zigolox** [comment]
The current state of the website is a combination between English and Swedish. Do you want me to find where there still are English translations or is this easy to in this [file](https://github.com/digitalungdom-se/digitalungdom.se/blob/master/locales/sv/translation.json) ?

**Comment by Nautman** [comment]
Make sure to use [localization for Material UI](https://material-ui.com/guides/localization/).
