### ISSUE TITLE
Regex for front-end link validation is wrong

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/digitalungdom.se#7]
The following line of code says that links ending with a `/` are invalid (eg. `foo.com/`, and that an `@`-symbol is an invalid link (e.g. `https://digitalungdom.se/@simson`.

https://github.com/digitalungdom-se/digitalungdom.se/blob/b6f0411593b29bed7a3069e45377ae22159f6c88/src/prod_components/userEditingForm.js#L109

This could be fixed by either getting a better regex, or creating a function that validates links.

Perhaps this could be modularised and put in a separate file, since this function or regex will probably be used several times.

Edit: Credit to Johan and Simon for finding this bug!

**Comment by kelszo** [comment]
See issue #12
