### ISSUE TITLE
Comments in a thread should not show if deleted

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#71]
Comments in a thread should be deleted if they don't have any stars.

It should perhaps also be possible to only enable deletion if the comment is very new eg. you can only delete your comment within 1h

**Comment by Nautman** [comment]
I think you should always be able to delete your comment. What do you mean by "Comments in a thread should be deleted if they don't have any stars."?

**Comment by Nautman** [comment]
This is the case in the rewrite. You can test yourself at https://dev.digitalungdom.se .
