### ISSUE TITLE
Current hamburger menu when window is small looks bad

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#76]
The hamburger menu  need re-styling

**Comment by Zigolox** [comment]
![image](https://user-images.githubusercontent.com/41542666/99573199-15c67580-29d6-11eb-88eb-517ee365bc96.png)

**Comment by Nautman** [comment]
Thanks for the image. It actually helps me get a quick overview of the problem and confirms that you see what I see.

Do you like this better?
<img width="564" alt="image" src="https://user-images.githubusercontent.com/28629647/99580405-5d013600-29d7-11eb-8c0c-2c9ad00eff57.png">

**Comment by Zigolox** [comment]
I think it looks better! I wounder although what order the menu items should come in. What does @charlesmaddock think?

**Comment by Nautman** [comment]
I switched the order: <img width="445" alt="image" src="https://user-images.githubusercontent.com/28629647/99581789-20363e80-29d9-11eb-84c2-416199ad4108.png">

Also moved the `ProfileHeaderButton`.

**Comment by Nautman** [comment]
Can you confirm if you like this? @Zigolox

**Comment by Zigolox** [comment]
I like it
