### ISSUE TITLE
Pressing the publish button should not be possible when not logged in or generate a pop-up

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#78]
The publish button in Agora dosn't check if the user in logged in or not and when writing an agoragram and pressing publish it dosn't work which is confusing.

**Comment by Nautman** [comment]
Do you think the button should be hidden or should generate a pop-up?

**Comment by Zigolox** [comment]
I think pop-up is better when pressing the button on the front-screen and the button should be disabled when trying to press it from within /agora/submit
