### ISSUE TITLE
Add random identicons for new users 

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/digitalungdom.se#79]
We should ask if we can use the code created by @adelhult to generate identicons. [The code can be found here](https://eli.nu/BotIdenticon/0.1/mod.js). It was written for deno so we might be able to get the Typescript version.

**Comment by Nautman** [comment]
I haven't prioritized this yet, but I'm thinking we could have a roadmap of something like this:

1. Convert to TypeScript
2. Make component into a reusable component
3. Change ownership to @digitalungdom-se and add @adelhult as a maintainer of the repository.
4. Publish the repository as an [organization scoped package](https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package) on npm. Then we can reuse it in several packages by `npm install @digitalungdom-se/bot-identicon`
5. Add the package as a dependency to this repository
6. Implement BotIdenticon in profile Avatar!

**Comment by Nautman** [comment]
Arter this I think we should make an announcement and social media posts that we have such a fantastic and engaged member that has made a cool package! 🤩

If it is published as a package it would also be possible to create a react app where you can customize a Bot Identicon!
